### ISSUE TITLE
"No module named 'bokeh'"   error when running psu in a venv

### ISSUE THREAD

**Issue by kiat-huang** [pjaos/rs310p_dc_psu#1]
First, I'm glad to have found this code as I've just got a new RS305p and I'm looking forward to getting access to it via the USB cable to my Ubuntu 20.10 box.

I've followed the installation instructions but running this always gives me this error.  I had installed bokeh in the virtualenv.  Google searches has not yielded a solution. Any ideas?

![Screenshot from 2021-10-07 00-16-35](https://user-images.githubusercontent.com/17239259/136296489-569390ab-66b1-40a2-af24-27399bb092dc.png)

**Comment by pjaos** [comment]
Sorry to see you're having some installation issues. I've taken a look at the code and noticed I wasn't checking for the explicit python version (python3 rather than python3.8). I've updated the installer to force the use of python3.8 (the version it was tested with). Could you try installing the updated python-rs3psu-1.5-all.deb installer and see how you get on. If you don't have python 3.8 installed then it will prompt you with the commands needed to install python3.8. If the installation fails initially, run the commands to install python3.8 and then installing the python-rs3psu-1.5-all.deb file again.

**Comment by pjaos** [comment]
I've updated to V1.6 to add a check that the pipenv module is installed. If you could let me know if this solves your issue. Thanks

**Comment by pjaos** [comment]
I posted a fix and have had no feedback on this issue so closing it
